# Generated by Django 5.0.14 on 2025-08-17 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Сообщение с формы',
                'verbose_name_plural': 'Сообщения с формы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('release_date', models.DateField(blank=True, help_text='Дата релиза', null=True)),
                ('work_start_date', models.DateField(blank=True, help_text='Начало работ', null=True)),
                ('work_end_date', models.DateField(blank=True, help_text='Окончание работ', null=True)),
                ('name', models.CharField(max_length=255, verbose_name='Название проекта')),
                ('subtitle', models.CharField(help_text='Краткое описание', max_length=255, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Полное описание')),
                ('link_google_play', models.URLField(blank=True, null=True, verbose_name='Google Play')),
                ('link_rustore', models.URLField(blank=True, null=True, verbose_name='RuStore')),
                ('link_appstore', models.URLField(blank=True, null=True, verbose_name='App Store')),
                ('link_github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/', verbose_name='Картинка')),
                ('category', models.CharField(choices=[('experience', 'Опыт'), ('freelance', 'Фриланс'), ('personal', 'Персональный')], default='personal', max_length=20, verbose_name='Категория')),
                ('extra_social_link', models.URLField(blank=True, null=True, verbose_name='Доп. ссылка (соцсеть)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Проект',
                'verbose_name_plural': 'Проекты',
                'ordering': ['-created_at'],
            },
        ),
    ]
