# Generated by Django 5.0.14 on 2025-08-17 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='Telegram')),
                ('github', models.URLField(blank=True, null=True, verbose_name='GitHub')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Соц. ссылки',
                'verbose_name_plural': 'Соц. ссылки',
            },
        ),
    ]
