# Generated by Django 5.0.14 on 2025-08-31 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_sociallinks'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Описание (EN)'),
        ),
    ]
